### ISSUE TITLE
Make SendResult more general to use

### ISSUE THREAD

**Issue by aCoder2013** [openmessaging/openmessaging-java#14]
Currently SendResult's messageId is a `String` , in my case ,message id is a object with custom field ,i wonder if it can be a generic type like `SendResult<T>` ? Thanks for you time
```java
public interface SendResult {
    /**
     * The unique message id related to the {@code SendResult} instance.
     *
     * @return the message id
     */
    String messageId();
}

```

**Comment by zhouxinyu** [comment]
Are the `custom fields` stored in some place?

**Comment by aCoder2013** [comment]
@zhouxinyu The messageId is actually a protobuf object , so i choose to transfer it into a base64 string

**Comment by vongosling** [comment]
@aCoder2013 Yes, welcome to do that~
