### ISSUE TITLE
support exclusive and non-exclusive consumer

### ISSUE THREAD

**Issue by qqeasonchen** [openmessaging/openmessaging-java#2]
![qq 20170328133626](https://cloud.githubusercontent.com/assets/26195189/24390454/96991896-13bb-11e7-9010-b2d4afe1b81e.png)

**Comment by vintagewang** [comment]
Is a good solution, if we can put the specific solution to scenes of abstracting, together to see whether the solution and openmessaging can complement each other.

**Comment by vongosling** [comment]
@qqeasonchen thanks for your suggestion, you could check out our newest API
