### ISSUE TITLE
Introduce Stream API

### ISSUE THREAD

**Issue by vesense** [openmessaging/openmessaging-java#23]
Currently, there are `Producer API`, `Consumer API` for basic IO operations on message queues.
For many scenes, users like to process messages in Streams.

The `Stream API` is **lightweight**, not as same as the distributed streaming systems like Apache Storm, Flink, Spark-Streaming.  And its implementation can be embeded in any java applications.

It provides the most common stream operations like `filter`,`flatMap`,`map`,`reduce`,`groupBy`,`join`,`count`,`max`,`min`,`window`, etc.

It's different from the existing `StreamingConsumer`, which is a low level Consumer API for processing consumer positions, etc. (IMHO, the class name of `StreamingConsumer` should be renamed to a more reasonable one, the current might be confused for users.)

**Comment by bsideup** [comment]
@vesense I created #20 for it. If OpenMessaging provides Reactive API then such operations can be plugged in by using RxJava, Akka Streams, Reactor or any other reactive framework

**Comment by bsideup** [comment]
@vesense but why not?

**Comment by vesense** [comment]
@bsideup 
The `Stream` API here, like Spark's DStream, Flink's DataStream or Kafka's KStream, is just stream abstraction including basic stream operations(`filter,flatMap,map,reduce,groupBy,join,count,max,min,window`, etc.).  This is the different point from reactive-streams's common reactive APIs(`Publisher, Subscriber, Subscription, Processor`). reactive-streams provides these  operations depending on _'RxJava, Akka Streams, Reactor or any other reactive framework'_. And another point is that it's easy and convenient to translate sql to `Stream` related operations when we consider supporting sql(e.g. flink-sql, kafka-ksql).

**Comment by vongosling** [comment]
@vesense how to support the Stream API base on the existing atomic API :-)

**Comment by vesense** [comment]
@vongosling Sorry for the delay because of my busy work. I will write a  google doc for the Stream API design after completing the RocketMQ-Beam integration. Thanks for your patience.
