### ISSUE TITLE
[question] Reference implementation ?

### ISSUE THREAD

**Issue by hypnoce** [openmessaging/openmessaging-java#27]
Hi,

I was wondering if there were any reference implementation on an existing queue (Rabbit, Kafka, Pulsar...) ? Would it make sense to provide some in openmessaging-contrib or openmessaging-impl repo ? Maybe it's out of scope of this project.

Thanks

-- 
François

**Comment by vongosling** [comment]
Thanks, @hypnoce. I will prepare some reference for the implementations once we are ready for the next version of the OpenMessaging.
