### ISSUE TITLE
direct message and persistent message

### ISSUE THREAD

**Issue by qqeasonchen** [openmessaging/openmessaging-java#3]
![qq 20170328134105](https://cloud.githubusercontent.com/assets/26195189/24390552/4271bed4-13bc-11e7-842a-0e070521d9aa.png)

direct message do not need dilivery into a queue, just direct send to a consumer

**Comment by zhouxinyu** [comment]
You could use `Producer->Queue->Consumer` and set the proper QoS for the Queue.
