### ISSUE TITLE
Extension Attributes & Interface

### ISSUE THREAD

**Issue by duhenglucky** [openmessaging/openmessaging-java#33]
Some attributes and interfaces are not universal in the current messaging and streaming field, but for now, most messaging middleware has implemented related concepts. such as store messages in different partitions, and in the form of the append-only log structure, assign each message with an offset for direct access.
So it is recommended to add extended attributes and interfaces to satisfy these message middleware. These attributes are not mandatory and may be removed or moved to mandatory fields.

**Comment by liyue2008** [comment]
Is there any way to get a instance for the new added interface io.openmessaging.extension.ExtensionClient.

There should be a getExcensionCleint method in the MessagingAccessPoint or other interfaces.
