### ISSUE TITLE
Feedback as promised

### ISSUE THREAD

**Issue by wu-sheng** [openmessaging/openmessaging-java#5]
Hi everyone, as I had promised a lot time ago. I am going to participate the discussion about **OpenMessaging**.  Before the discussion about details, I have some suggestions and questions.

* Is the OpenMessage a language independency specification?
If not, ignore this. Otherwise, why the API descriptions are Java-specific? I think this is one of the most important thing at beginning. You said: this spec is **vendor-neutral**, you should be careful with that. Can't guarantee that, each vendor uses Java. Right?

* No specification documents can be found in the repository.
I just found and read the pdf: https://github.com/openmessaging/openmessaging/blob/master/docs/OpenMessagingDomainArchitecture-v1.0.pdf. But from its name, it is not a specification, even not a alpha version. But the contents like one. Please correct me if I misunderstand.

* All documents should be in **markdown** format.
Why **markdown** format is so important? The specification is for people to discuss and change, right? But, how can I change a pdf through a pr?

* No contributors or participators list.
As you known, OpenTracing use OTSC and OTIAB, and also use github org to group people together( public members and badges in their profile). And I want to start a discuss, I know who should be mentioned in the issue. And be very helpful for spec populariztion. That is also **Why I asked you to invite me into the group** last time.

* Code should be isolated from this repository.
Specification is nothing about **Code**, even in JSR, right? So even we are only Java-specific, we should move the codes to an independency repository.

@vongosling Hope these will help you.

**Comment by wu-sheng** [comment]
I found this in your org description: **Cloud-oriented, simple, flexible, vendor-neutral and language-independent standards for messaging**. It specified this **language-independent**, so , I am sure the spec should be no Java native codes or docs.

**Comment by wu-sheng** [comment]
#4 has confirmed my concern about that, you can't pull request anything to fix a pdf doc. No matter #4 is right or wrong, it is irrelative.

**Comment by zhouxinyu** [comment]
Hi @wu-sheng , many thanks for your suggestions, we will resolve them one by one soon to let other contributors can participate in OMS easily~  As a initial project, there are many things should be improved, hope we can learn valuable experience from OpenTracing.

**Comment by wu-sheng** [comment]
@zhouxinyu Don't worry, open source always has time. I comment all these because I promised @vongosling long time ago. So here we are.
