### ISSUE TITLE
Not a issue , but a question

### ISSUE THREAD

**Issue by ksingh7** [openmessaging/openmessaging-java#58]
Scenario: Suppose i already have a production instance of Kafka running in my infrastructure and i wanted to benchmark my Kafka cluster using this project. 

Question: Does Openmessaging allow me to do that, without spinning a new AWS infra/Kafka cluster 

If yes, can you please share an example to connect to external kafka endpoint ( any config file will be helpful as well.

**Comment by duhenglucky** [comment]
@ksingh7 yes, you can use this [the OpenMessaging benchmark tools](https://github.com/openmessaging/openmessaging-benchmark) to do more test with kafka and other messaging middleware, and OpenMessaging benchmark used terraform to create resources, but if you have already launched a cluster, please use the benchmark client test it directly.

**Comment by ksingh7** [comment]
Thanks @duhenglucky  appretiate your help
