### ISSUE TITLE
Add region, account_id properties to OMS driver URL

### ISSUE THREAD

**Issue by zhouxinyu** [openmessaging/openmessaging-java#9]
Currently, OMS driver URL schema is:

```
oms:<driver_type>://<access_point>[,<access_point>,...]/<namespace>
```

The only user-oriented property is `namespace`, which is not enough to handle many complicated scenarios, like multiple tenants, environment isolation, AB tests, etc.

Consider adding region and account_id properties to OMS driver URL.

**Comment by vintagewang** [comment]
username  is equivalent to AppId，ProjectId。
It is used to identify the resource belongs to who

**Comment by zhouxinyu** [comment]
New alternative schema:

```
oms:<driver_type>://<username>@<access_point>[,<access_point>,...]/<region>:<namespace>
```

For example：
```
oms:rocketmq://alice@openmessaging.cloud,rocketmq.org/us-east:default_space
oms:rocketmq://bob@openmessaging.cloud/us-east:default_space
```

**Comment by zhouxinyu** [comment]
Access point schema:

https://github.com/openmessaging/specification/blob/master/oms_access_point_schema.md

**Comment by vongosling** [comment]
URI still include the password of the username(accout_id).
